version: '3.2'
services:
    digi-nginx:
        build: .
        container_name: digi-nginx-1
        logging:
            driver: "gelf"
            options:
                gelf-address: "udp://localhost:12201"
        ports:
            - "8080:3012"
        #volumes:
        #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
