---
- hosts: all

  vars:
    - artifactory_database: postgres
    - base_postgres_user: test_db_user
    - base_postgres_pass: test_password

  roles:
    - role: java
#    - role: postgresql
#    - role: artifactory
